-- Generated by HyprMod

-- Settings
hl.config({
    decoration = {
        blur = {
            enabled = false,
        },
        inactive_opacity = 1.0,
        rounding = 7,
        rounding_power = 2.0,
    },
    general = {
        allow_tearing = false,
        col = {
            active_border = "0xff3d3846",
            inactive_border = "0x1193a1a1",
        },
        snap = {
            enabled = false,
        },
    },
    gestures = {
        workspace_swipe_touch = false,
        workspace_swipe_use_r = true,
    },
    input = {
        scroll_factor = 1.0,
        sensitivity = 0.6,
        touchpad = {
            scroll_factor = 0.9,
        },
    },
    misc = {
        vrr = 0,
    },
})

-- Bezier curves
hl.curve("custom1", { type = "bezier", points = { {0.0, 0.951}, {0.993, -0.031} } })

-- Animations
hl.animation({
    leaf = "borderangle",
    enabled = true,
    speed = 1.0,
    bezier = "custom1",
    style = "once",
})
