$video_bg = pkill mpvpaper ; mpvpaper -l top -vs -o "no-audio loop" '*' ~/Pictures/New\ Folder/bg.mp4 -f

listener {
    timeout = 60
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

listener {
    timeout = 900
    on-timeout = systemctl suspend
    on-resume = brightnessctl -r ; pidof hyprlock || ($video_bg ; hyprlock ; pkill mpvpaper)
}

general {
    before_sleep_cmd = notify-send "Going to sleep"
    after_sleep_cmd = brightnessctl -r ; pidof hyprlock || ($video_bg ; hyprlock ; pkill mpvpaper)
    ignore_dbus_inhibit = false
    ignore_systemd_inhibit = false
}
